application: celebrationclassic
version: 5
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /(register|continue|postpayment|fakeacceptiva)
  script: register.py

- url: /admin/.*
  script: admin.py
  login: required

- url: /auction.html
  script: auction.py

- url: /.*
  script: proxy.py
