application: celebrationclassic
version: 8
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

builtins:
- remote_api: on

handlers:
- url: /favicon\.png
  static_files: favicon.png
  upload: favicon.png

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /(register|continue|relayresponse|receipt|postpayment|fakeacceptiva)
  script: register.app

- url: /admin/.*
  script: admin.app
  login: required

- url: /auction
  script: auction.app

- url: /img/.*
  script: auction.app

- url: /(photos|files)/.*
  script: uploads.app

- url: /.*
  script: detailpagehandler.app

libraries:
- name: webob
  version: "1.2.3"

- name: webapp2
  version: "2.5.2"

- name: django
  version: "1.4"
