application: celebrationclassic
version: 6
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

builtins:
- remote_api: on

handlers:
- url: /favicon\.png
  static_files: favicon.png
  upload: favicon.png

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /(register|continue|postpayment|fakeacceptiva)
  script: register.app

- url: /admin/.*
  script: admin.app
  login: required

- url: /auction.html
  script: auction.app

- url: /img/.*
  script: auction.app

- url: /(index|details|sponsor|volunteer|map|raffle)\.html
  script: detailpagehandler.app

- url: /.*
  script: proxy.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: django
  version: "1.2"
