from google.appengine.ext import db

class Sponsor(db.Model):
	id = db.IntegerProperty(default = 0)
	name = db.StringProperty()
	company = db.StringProperty()
	address = db.StringProperty()
	city = db.StringProperty()
	phone = db.StringProperty()
	fax = db.StringProperty()
	email = db.StringProperty()
	anonymous = db.BooleanProperty()
	printed_names = db.StringProperty()
	sponsorships = db.ListProperty(db.Key)
	num_golfers = db.IntegerProperty()
	num_dinners = db.IntegerProperty()
	payment_due = db.IntegerProperty()
	payment_made = db.IntegerProperty()
	payment_type = db.StringProperty()
	transaction_code = db.StringProperty()
	pairing = db.StringProperty()
	dinner_seating = db.StringProperty()
	timestamp = db.DateTimeProperty(auto_now_add = True)

class Golfer(db.Model):
	sequence = db.IntegerProperty()
	name = db.StringProperty()
	gender = db.StringProperty()
	title = db.StringProperty()
	company = db.StringProperty()
	address = db.StringProperty()
	city = db.StringProperty()
	phone = db.StringProperty()
	email = db.StringProperty()
	golf_index = db.StringProperty()
	best_score = db.StringProperty()
	ghn_number = db.StringProperty()
	shirt_size = db.StringProperty()
	dinner_choice = db.StringProperty()

class DinnerGuest(db.Model):
	sequence = db.IntegerProperty()
	name = db.StringProperty()
	dinner_choice = db.StringProperty()
